"""empty message

Revision ID: 657c546d4743
Revises: 819013da309a
Create Date: 2022-08-25 15:24:12.856042

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '657c546d4743'
down_revision = '819013da309a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('test', sa.ARRAY(sa.String(length=120)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'test')
    # ### end Alembic commands ###
